// src/app/cleaning/mock-data/monsters.ts
import type { Monster } from '../types'

export const MONSTERS: Monster[] = [
  {
    id: 'slime-mold',
    name: '물때 분열 슬라임',
    grade: 'E',
    location: '욕실 · 싱크대',
    icon: '💧',
    ability: '분열',
    abilityDesc: '48h 방치 시 2마리로 복제. 타임어택 15분 내 처치 시 즉사.',
    exp: 40,
    gold: 15,
    requiresPhoto: false,
    splitOnNeglect: { hours: 48 },
    timeAttackWeakness: true,
  },
  {
    id: 'dust-ghost',
    name: '먼지 투명 유령',
    grade: 'E',
    location: '거실 · 침실 · 선반 밑',
    icon: '👻',
    ability: '투명화',
    abilityDesc: '퀘스트 목록에 표시 안 됨. 청소하다 발견 시 히든 게이트 이벤트 + EXP×3.',
    exp: 60,
    gold: 20,
    requiresPhoto: false,
    isHidden: true,
  },
  {
    id: 'toilet-guardian',
    name: '변기 오염 가디언',
    grade: 'B',
    location: '화장실 — 변기',
    icon: '🦠',
    ability: '재생',
    abilityDesc: '불완전 청소 시 HP 회복. 포토 인증으로만 처치 확정. AI 불완전 판정 시 HP 30% 회복.',
    exp: 120,
    gold: 45,
    requiresPhoto: true,
  },
  {
    id: 'dish-golem',
    name: '설거지 산더미 골렘',
    grade: 'A',
    location: '주방 — 싱크대',
    icon: '🗻',
    ability: '축적',
    abilityDesc: '매 6h마다 HP +20% 증가. 2인 이상 파티 레이드 권장. 솔플 시 EXP 50% 감소.',
    exp: 200,
    gold: 80,
    requiresPhoto: false,
    raidRequired: true,
  },
  {
    id: 'trash-overlord',
    name: '쓰레기 더미 마왕',
    grade: 'S',
    location: '거실 · 주방 — 쓰레기통',
    icon: '🧟',
    ability: '악취 결계',
    abilityDesc: '72h 방치 시 인접한 모든 방에 던전 브레이크 발동. 어지럽히기로 강화 소환 가능.',
    exp: 350,
    gold: 140,
    requiresPhoto: false,
  },
  {
    id: 'fridge-relic',
    name: '냉장고 고대 유물',
    grade: 'C',
    location: '주방 — 냉장고 내부',
    icon: '🧊',
    ability: '봉인',
    abilityDesc: '방치 기간에 따라 D→C→B→A 등급 상승. 유통기한 확인 + 버리기로 처치. 클리어 시 골드 드랍.',
    exp: 80,
    gold: 30,
    requiresPhoto: false,
  },
  {
    id: 'laundry-lord',
    name: '빨랫감 산맥 군주',
    grade: 'B',
    location: '세탁실 · 침실 바닥',
    icon: '🌋',
    ability: '압도',
    abilityDesc: '타임어택 불가. 세탁→건조→개기 단계 처치만 유효.',
    exp: 130,
    gold: 50,
    requiresPhoto: false,
    timeAttackWeakness: false,
  },
  {
    id: 'chaos-lord',
    name: '강화 카오스 군주',
    grade: '??',
    location: '어지럽히기 소환 전용',
    icon: '😈',
    ability: '카오스 강화',
    abilityDesc: 'EXP×3 보상. 24시간 데드라인. 미처치 시 페널티존 #5 확정.',
    exp: 999,
    gold: 400,
    requiresPhoto: true,
  },
]
