// src/app/cleaning/mock-data/penalty-zones.ts
import type { PenaltyZone } from '../types'

export const PENALTY_ZONES: PenaltyZone[] = [
  {
    id: 'desert',
    name: '먼지 지옥 사막',
    subtitle: 'PENALTY ZONE #1',
    icon: '🏜️',
    bgFrom: '#1a1000',
    bgTo: '#2d1800',
    borderColor: 'rgba(180,100,0,0.4)',
    entryCondition: '일반 퀘스트 미완료',
    escapeMission: '10분 내 방 1칸 청소 인증',
    escapeDetail: '어떤 방이든 1칸을 완전히 청소하고 인증샷을 제출하십시오.',
  },
  {
    id: 'trash',
    name: '쓰레기 산 분리수거 지옥',
    subtitle: 'PENALTY ZONE #2',
    icon: '🗑️',
    bgFrom: '#001a10',
    bgTo: '#002d1a',
    borderColor: 'rgba(0,180,80,0.3)',
    entryCondition: '쓰레기 마수 72h 방치',
    escapeMission: '분리수거 30개 정확 분류',
    escapeDetail: '현실에서 쓰레기를 분리수거하고 완료 인증샷을 제출하십시오.',
  },
  {
    id: 'toilet',
    name: '극한 화장실 던전',
    subtitle: 'PENALTY ZONE #3',
    icon: '🚽',
    bgFrom: '#0d001a',
    bgTo: '#1a002e',
    borderColor: 'rgba(139,92,246,0.4)',
    entryCondition: '변기 가디언 3일 방치',
    escapeMission: '화장실 청소 포토 인증 (AI B+ 판정)',
    escapeDetail: '화장실 전체를 청소하고 AI 청결도 80% 이상 판정을 받으십시오.',
  },
  {
    id: 'laundry',
    name: '빨랫감 산맥 정상',
    subtitle: 'PENALTY ZONE #4',
    icon: '🌋',
    bgFrom: '#1a0500',
    bgTo: '#2d0a00',
    borderColor: 'rgba(220,80,0,0.4)',
    entryCondition: '빨래 산맥 군주 방치',
    escapeMission: '세탁→건조→개기 단계 인증 완료',
    escapeDetail: '빨래의 전 과정(세탁기 → 건조 → 개어서 정리)을 단계별로 인증하십시오.',
  },
  {
    id: 'chaos',
    name: '카오스 의식 실패 심연',
    subtitle: 'PENALTY ZONE #5 — 특수',
    icon: '💀',
    bgFrom: '#1a0000',
    bgTo: '#2e0000',
    borderColor: 'rgba(220,38,38,0.5)',
    entryCondition: '어지럽히기 24h 미처치',
    escapeMission: '화장실 + 거실 동시 포토 인증',
    escapeDetail: '화장실과 거실을 동시에 청소하고 두 공간 모두 인증샷을 제출하십시오.',
  },
]
